### ISSUE TITLE
使用最新版的高德地图SDK 2.6 报错

### ISSUE THREAD

**Issue by HaishengLiang** [cysgit/iOS_MovingAnnotation_Demo#2]
@interface MAMapView(Additional)
- (CGPoint)pointForMapPoint:(MAMapPoint)mapPoint;

@end

这个方法不生效
能提供下解决方案么？

**Comment by machinefixer** [comment]
同问，这个类扩展只有声明没有实现

**Comment by cysgit** [comment]
这个接口的实现封装在framework里了

**Comment by machinefixer** [comment]
@cysgit Thanks!

**Comment by CoderXXLee** [comment]
使用2D地图
@interface MAMapView(Additional)

(CGPoint)pointForMapPoint:(MAMapPoint)mapPoint;
@end
这个方法不生效

**Comment by cysgit** [comment]
已更新至4.0.1
